### ISSUE TITLE
Local repository only, want git add/commit/tag but not push

### ISSUE THREAD

**Issue by dcd271b2** [TankerHQ/tbump#65]
I have a local repository (no remotes) and I want to use tbump.  I still want the git add/commit/tag operations but I don't want/need a push.  Right now, tbump is all-or-nothing with git operations and the --only-patch option.  Can there be a --local-only option or something to do everything but the push?

**Comment by dmerejkowsky** [comment]
> Can there be a --local-only option or something to do everything but the push?

I guess so. I'd rather use an option named `--no-git-push`, which I think express the behavior more clearly

**Comment by ygworldr** [comment]
> @dcd271b2 still wants the tag, just not the push. I want neither tag nor tag push but I do want the commit. Ah, the joys of users causing trouble⸮

Just so all the information is on one page. 

Yes, I am happy with a `--no-tag` option so I can run `tbump 1.2.3 --no-tag --no-push` to just get the commit.

**Comment by dmerejkowsky** [comment]
Cool :+1:

**Comment by dmerejkowsky** [comment]
This was implemented in the 6.3.0 release. Let's close this
