### ISSUE TITLE
pyproject.toml support

### ISSUE THREAD

**Issue by pmav99** [TankerHQ/tbump#69]
Since the configuration file is in TOML it shouldn't be too difficult to use `pyproject.toml` as the configuration file. Thoughts?

**Comment by dmerejkowsky** [comment]
I like the idea :)

**Comment by pmav99** [comment]
I made a Pull Request that handles Option 2.

**Comment by dmerejkowsky** [comment]
Thanks for doing the PR, but I have concerns with Option 2.

First off, even if we broke retro-compatibility a few times, it's still something we prefer not to do if we have a choice.

Second, ` tbump` is not used solely with Python projects. Replacing `tbump.toml`  with `pyproject.toml` for a Javascript library would make little sense for its maintainers.

For these two reasons, I think we should go with Option 1, even if it does require a bit more code.

**Comment by pmav99** [comment]
I am copying from the PR review:

>  I think you should keep tests running with tbump.toml, and add just one test dedicated on pyproject.toml support.
> [...]
> it will crash with KeyError if [tool] or [[tool.tbump]] section is missing

The main "problem" is that `tbump.toml` and `pyproject.toml` use different "schemas". 

`tbump.toml` uses flat keys/sections, while `pyproject.toml` uses nested ones. Furthermore the tests often have hardcoded not just the configuration filename but the keys too ([example](https://github.com/TankerHQ/tbump/blob/dbe851470243c56f12b41c28789eab92432b581f/tbump/test/test_file_bumper.py#L56-L75)). Consequently I don't really see how `pyproject.toml` can be thoroughly tested unless the tests are duplicated or heavily refactored (with some creative usage of pytest fixtures).

> Note: Technically speaking it should be possible to insert flat keys into `pyproject.toml` too, but that would be against [PEP-518](https://www.python.org/dev/peps/pep-0518/#tool-table).

**Comment by pmav99** [comment]
I think that supporting option 1 requires some refactoring. Therefore I started to work on a new branch and I made a new PR.

Among other things, there are some issues that need to be discussed WRT the API. E.g. if both formats/schemas are to be valid and in use, then `tbump init` should offer a way to choose between the two (e.g. via a `--use-pyproject` flag or something). I did something, but you might prefer something else. 

The PR is still WIP and I rebase often, but I would appreciate if you could have a quick look so that I have some high level feedback whether you are OK with where the changes are going.
